### ISSUE TITLE
Image with alpha becomes bluish

### ISSUE THREAD

**Issue by shmidt** [seanooi/iOS-WebP#2]
I suddenly found, that there is some problem with alpha, when saving it to webp.
I changed your example to demonstrate it.  
https://www.dropbox.com/s/bjww7ud4n7qhsgn/iOS-WebP-master-alpha.zip

This is the result of saving webp with transparency:
![ios simulator screen shot 10 jan 2014 12 54 34](https://f.cloud.github.com/assets/1472370/1885683/da828b3e-79d4-11e3-8811-28d9ae065b40.png)

**Comment by newacct** [comment]
It seems that the "fix" of Jan 12, 2014 mentioned above (commit 1664801, "Added function for image with transparency") was for some unexplained reason reverted by a commit on Jan 20, 2014 (commit e72ea1c, "Fixed alpha channel showing dark gray background when alpha is < 1").
